export default {
    whiteColor: '#FFFFFF',
    headerColor: '#9AE483',
    inputBackgroundColor: '#E9EAEA',
    seperatorColor: '#C9C9C9',
    blackColor: '#090808',
    redColor: 'red',
    grayColor: 'gray',
    backgroundColor: '#EEF3F7',
    healthCardColor: '#0DCAD0',
    inquiryColor : '#F0306B',
    reminderColor: '#23B8FF',
    intimationColor: '#2189FF',
    secondaryInputBackgroundColor : '#EEEEEE',
    shadowColor: '#00000040',
    secondaryTextColor: '#0C0C0C80',
    activeBottomTintColor: '#5BC23E',
    secondaryBackgroundColor: '#555E55',
    inProgressTextColor: '#1FA9E3',
    declineColor: '#E3675F',
    borderColor: '#DDDDDD',
    searchBGColor: '#555D55',
};
